return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  config = function()
    local ensure_installed = {
      "bash",
      "c",
      "cpp",
      "fish",
      "gitcommit",
      "go",
      "graphql",
      "html",
      "hyprlang",
      "java",
      "javascript",
      "json",
      "json5",
      "lua",
      "markdown",
      "markdown_inline",
      "nix",
      "python",
      "query",
      "rasi",
      "regex",
      "rust",
      "scss",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    }

    require("nvim-treesitter").install(ensure_installed, { skip = { installed = true } })
  end,
}
