return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "fish",
      "gitcommit",
      "go",
      "graphql",
      "html",
      "hyprlang",
      "java",
      "javascript",
      "json",
      "json5",
      "jsonc",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "rasi",
      "regex",
      "rust",
      "scss",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
    highlight = { enable = true },
    indent = {
      enable = true,
      -- Treesitter unindents Yaml lists for some reason.
      disable = { "yaml" },
    },
  },
}
